eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10017/eureka/
server:
  port: 11012
spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: eurekaclient
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
