eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10087/eureka/
server:
  port: 9898
spring:
  sender:
    type: web
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  application:
    name: eurekaclient
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
