eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10017/eureka/
server:
  port: 11012
spring:
  zipkin:
    #base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
    sender:
      #type: rabbit
      type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    listener: # 这里配置了重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: eurekaclient
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
