eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10087/eureka/
server:
  port: 11082
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: eurekaclient
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
